version: '3.9'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - backnet

  postgres:
    container_name: postgresprisma
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - backnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/var/log/myLogs
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

networks:
  backnet:
    name: ${NETWORK}
    driver: ${DRIVER}

volumes:
  postgres_data:
    name: db
  postgres_log:
    name: log