version: '3.9'

services:

  db:
    build: ./postgres/
    restart: always
    networks:
      - backend_network
    shm_size: 128mb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  backend_network:
    driver: bridge  