version: '3.9'

services:

  # nest:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - ${PORT}:${PORT}
  #   volumes:
  #     - ./src:/usr/app/src
  #   networks:
  #     - backnet


  db:
    container_name: postgresdb
    build: ./postgres/
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    networks:
      - backnet
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_log:/var/log/myLogs
    ports:
      - ${PGPORT}:${PGPORT}

  adminer:
    image: adminer
    restart: always
    networks:
      - backnet
    ports:
      - 8080:8080

networks:
  backnet:
    name: ${NETWORK}
    driver: ${DRIVER}
