# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    networks:
      - backend_network
    shm_size: 128mb
    environment:
      POSTGRES_DB: "rssdb"
      POSTGRES_USER: "rssuser"
      POSTGRES_PASSWORD: "rsspassword"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - backend_network
    ports:
      - 8080:8080

networks:
  backend_network:
    driver: bridge  