version: '3.9'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - backnet

  postgres:
    container_name: postgresprisma
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    networks:
      - backnet
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./postgres_data:/var/lib/postgresql/data
      # - ./postgres_log:/var/log/myLogs
    ports:
      - ${PGPORT}:${PGPORT}

networks:
  backnet:
    name: ${NETWORK}
    driver: ${DRIVER}

volumes:
  postgres:
    name: nest-prisma-docker-db